[theme]
primaryColor = "#00B386"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true
hideFooter = true